---
title: Aelindgard's Journal
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    share: true
remote_theme: mmistakes/so-simple-theme@3.2.0
skin: "/assets/css/skins/dark.css"
locale: en-US
description: A collection of random randomness.
baseurl: 
url: https://www.aelindgard.com
logo: "/images/global/aelindgard.jpg"
date_format: "%d %m %Y"
read_time: true
words_per_minute: 200
mathjax: 
google_fonts:
- name: Source Sans Pro
  weights: 400,400i,700,700i
- name: Lora
  weights: 400,400i,700,700i
google_analytics: 
disqus:
  shortname: 
twitter:
  username: aelindgard
liquid:
  error_mode: strict
permalink: "/:categories/:title/"
markdown: kramdown
feed:
  path: atom.xml
include:
- _pages
paginate: 10
paginate_path: "/page:num/"
search_full_content: false
plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
- jekyll-paginate
author:
  name: Aelindgard
  picture: "/images/global/aelindgard.jpg"
  email: aelindgard@outlook.com
  twitter: aelindgard
  links:
  - title: Twitter
    url: https://twitter.com/aelindgard
    icon: fab fa-twitter-square
  - title: Instagram
    url: https://instagram.com/aelindgard
    icon: fab fa-instagram
  - title: GitHub
    url: https://github.com/aelindgard
    icon: fab fa-github-square
footer_links:
- title: Twitter
  url: https://twitter.com/aelindgard
  icon: fab fa-twitter-square
- title: Instagram
  url: https://instagram.com/aelindgard
  icon: fab fa-instagram
- title: GitHub
  url: https://github.com/aelindgard
  icon: fab fa-github-square
- title: Feed
  url: atom.xml
  icon: fas fa-rss-square
